
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftADDSUBleftMULDIVrightNEGnonassocPOWADD DIV ENDL LPAREN MUL NUM POW RPAREN SUBline : expr ENDLline : error ENDLexpr : numberexpr : LPAREN expr RPARENexpr : SUB LPAREN expr RPAREN %prec NEGexpr : expr ADD exprexpr : expr SUB exprexpr : expr MUL exprexpr : expr POW expr_in_powerexpr : expr DIV exprexpr_in_power : number_in_powerexpr_in_power : LPAREN expr_in_power RPARENexpr_in_power : SUB LPAREN expr_in_power RPAREN %prec NEGexpr_in_power : expr_in_power ADD expr_in_powerexpr_in_power : expr_in_power SUB expr_in_powerexpr_in_power : expr_in_power MUL expr_in_powernumber : NUMnumber : SUB number %prec NEGnumber_in_power : NUMnumber_in_power : SUB number_in_power %prec NEG'
    
_lr_action_items = {'error':([0,],[3,]),'LPAREN':([0,5,6,9,10,11,12,13,17,24,25,30,31,32,35,],[5,5,17,5,5,5,24,5,5,24,35,24,24,24,24,]),'SUB':([0,2,4,5,6,7,9,10,11,12,13,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,],[6,10,-3,6,16,-17,6,6,6,25,6,10,16,6,-18,-6,-7,-8,-9,-11,25,34,-19,-10,-4,10,25,25,25,31,34,25,-20,-5,-14,-15,-16,-12,31,-13,]),'NUM':([0,5,6,9,10,11,12,13,16,17,24,25,30,31,32,34,35,],[7,7,7,7,7,7,26,7,7,7,26,26,26,26,26,26,26,]),'$end':([1,8,14,],[0,-1,-2,]),'ENDL':([2,3,4,7,18,19,20,21,22,23,26,27,28,36,37,38,39,40,41,43,],[8,14,-3,-17,-18,-6,-7,-8,-9,-11,-19,-10,-4,-20,-5,-14,-15,-16,-12,-13,]),'ADD':([2,4,7,15,18,19,20,21,22,23,26,27,28,29,33,36,37,38,39,40,41,42,43,],[9,-3,-17,9,-18,-6,-7,-8,-9,-11,-19,-10,-4,9,30,-20,-5,-14,-15,-16,-12,30,-13,]),'MUL':([2,4,7,15,18,19,20,21,22,23,26,27,28,29,33,36,37,38,39,40,41,42,43,],[11,-3,-17,11,-18,11,11,-8,-9,-11,-19,-10,-4,11,32,-20,-5,32,32,-16,-12,32,-13,]),'POW':([2,4,7,15,18,19,20,21,22,23,26,27,28,29,36,37,38,39,40,41,43,],[12,-3,-17,12,-18,12,12,12,-9,-11,-19,12,-4,12,-20,-5,-14,-15,-16,-12,-13,]),'DIV':([2,4,7,15,18,19,20,21,22,23,26,27,28,29,36,37,38,39,40,41,43,],[13,-3,-17,13,-18,13,13,-8,-9,-11,-19,-10,-4,13,-20,-5,-14,-15,-16,-12,-13,]),'RPAREN':([4,7,15,18,19,20,21,22,23,26,27,28,29,33,36,37,38,39,40,41,42,43,],[-3,-17,28,-18,-6,-7,-8,-9,-11,-19,-10,-4,37,41,-20,-5,-14,-15,-16,-12,43,-13,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'line':([0,],[1,]),'expr':([0,5,9,10,11,13,17,],[2,15,19,20,21,27,29,]),'number':([0,5,6,9,10,11,13,16,17,],[4,4,18,4,4,4,4,18,4,]),'expr_in_power':([12,24,30,31,32,35,],[22,33,38,39,40,42,]),'number_in_power':([12,24,25,30,31,32,34,35,],[23,23,36,23,23,23,36,23,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> line","S'",1,None,None,None),
  ('line -> expr ENDL','line',2,'p_line_expr','yaccrules.py',15),
  ('line -> error ENDL','line',2,'p_line_error','yaccrules.py',23),
  ('expr -> number','expr',1,'p_expr_number','yaccrules.py',33),
  ('expr -> LPAREN expr RPAREN','expr',3,'p_expr_paren','yaccrules.py',39),
  ('expr -> SUB LPAREN expr RPAREN','expr',4,'p_expr_neg','yaccrules.py',43),
  ('expr -> expr ADD expr','expr',3,'p_expr_add','yaccrules.py',49),
  ('expr -> expr SUB expr','expr',3,'p_expr_sub','yaccrules.py',55),
  ('expr -> expr MUL expr','expr',3,'p_expr_mul','yaccrules.py',61),
  ('expr -> expr POW expr_in_power','expr',3,'p_expr_pow','yaccrules.py',67),
  ('expr -> expr DIV expr','expr',3,'p_expr_div','yaccrules.py',73),
  ('expr_in_power -> number_in_power','expr_in_power',1,'p_expr_in_exponent_number','yaccrules.py',84),
  ('expr_in_power -> LPAREN expr_in_power RPAREN','expr_in_power',3,'p_expr_in_exponent_paren','yaccrules.py',90),
  ('expr_in_power -> SUB LPAREN expr_in_power RPAREN','expr_in_power',4,'p_expr_in_exponent_neg','yaccrules.py',94),
  ('expr_in_power -> expr_in_power ADD expr_in_power','expr_in_power',3,'p_expr_in_exponent_add','yaccrules.py',100),
  ('expr_in_power -> expr_in_power SUB expr_in_power','expr_in_power',3,'p_expr_in_exponent_sub','yaccrules.py',106),
  ('expr_in_power -> expr_in_power MUL expr_in_power','expr_in_power',3,'p_expr_in_exponent_mul','yaccrules.py',112),
  ('number -> NUM','number',1,'p_number_pos','yaccrules.py',118),
  ('number -> SUB number','number',2,'p_number_neg','yaccrules.py',122),
  ('number_in_power -> NUM','number_in_power',1,'p_number_in_pow_pos','yaccrules.py',126),
  ('number_in_power -> SUB number_in_power','number_in_power',2,'p_number_in_powewr_neg','yaccrules.py',130),
]
